### ISSUE TITLE
[ios] the option to hide/display the close button is not implemented

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#10]
I reproduce this on iOS, I've not tested yet on Android.
The close button is always present, whether the option is set to true or false in the javascript code.
In the mapwize.m and in the viewcontroller.m files, the showCloseButton boolean is always set to YES and is not get from the cordova command arguments.

It's not blocking me (on iOS the button should always be present), it's for your information.

**Comment by laszloblum** [comment]
Thanks for the report. Will be fixed in the next push of offlineManager branch.

**Comment by mathieugerard** [comment]
This issue has been fixed in the master branch.
