### ISSUE TITLE
[ios/android] the shouldShowInformationButtonFor callback never receives arguments

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#11]
The callback is triggered when the information panel is displayed but the args is always undefined.
See screenshot below:
![Capture d’écran 2019-04-26 à 15 28 30](https://user-images.githubusercontent.com/10091017/56811335-c55a5680-6838-11e9-9aa8-150d88a3e62b.png)

**Comment by laszloblum** [comment]
Yes, it is hardcoded. We need to discuss on the requirements in order to make this functionality feasible in cordova.

**Comment by mathieugerard** [comment]
Specifications are being defined and the feature implemented. It will be a combination of object data and default that will define if the info button is displayed or not. The behavior used in native is not feasible in Cordova.

**Comment by mathieugerard** [comment]
Hi. The showInformationButton behavior has been improved and is now available on the master branch. The showInformationButtonForPlaces and showInformationButtonForPlaceLists options allows to define the default value for display based on the object type. This default can be rewritten by adding the key cordovaShowInformationButton in the place or placeList data.

**Comment by EmeryGuillaume** [comment]
Hi @mathieugerard,

If I don't misunderstand, the showInformationButtonForPlaces/showInformationButtonForPlaceLists is "all-or-nothing", i.e. it displays the Information button for all the places or for none. That doesn't help me for this scenario as I won't be able to show information for a given place (in our case, exhibitors) and not for other (session rooms). Please correct me if I'm wrong.

The cordovaShowInformationButton is a data stored in your database, right? I have nothing to implement in order to make it work?

Thanks for your feedback.

**Comment by laszloblum** [comment]
Hi @EmeryGuillaume,
Correct, they are "all-or-nothing" based. For, a particular object you should use cordovaShowInformationButton data attached to the object (and of course set the appropriate  showInfo...  to false). No implementation needed for the later, but assign the cordovaShowInformationButton in the mapwize editor.

**Comment by EmeryGuillaume** [comment]
Hi @laszloblum, thanks for your feedback.
