### ISSUE TITLE
[ios] unable to close the Mapwize view controller from javascript context

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#2]
On iOS when I instantiate a new Mapwize view (using Mapwize.createMapwizeView), I am unable to close it from the Javascript context.
I receive data into the javascript app but I need a method to hide the iOS native viewcontroller.

Not tested on Android but I assume the back button should kill the activity (but a dedicated method is required too to ensure coherence between the two platforms).

**Comment by mathieugerard** [comment]
Hi Guillaume, that's right, the close function is still missing and will be added very shortly. Also, we are planning to add a close button on view so that users can close the modal view and come back to the app. We'll let you know as soon as this is ready.

**Comment by laszloblum** [comment]
Fixed in closeView branch

**Comment by mathieugerard** [comment]
The branch has been merged with Master. There is a now a button and a function to close the view on both iOS and Android

**Comment by EmeryGuillaume** [comment]
@mathieugerard I've tested on iOS: the view closes when I tap on Done but the event TapOnCloseButton is never fired. I've made a fix, I'll submit a PR.

**Comment by EmeryGuillaume** [comment]
Hi @mathieugerard, any idea on when you can review and (hopefully) merge the PR?
