### ISSUE TITLE
[android] unable to reopen the map when the app has been put in background

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#23]
**Steps to reproduce**
Open the app
open the mapwize map
click on home button to put the app in background
open the app previously in background 
-> you see here that the app totally refresh
-> now it's impossible to reopen the map.

On some devices, there is a strange behavior, the app forks in the task manager (see attachment)
![Capture d’écran 2019-05-10 à 14 10 41](https://user-images.githubusercontent.com/10091017/57526327-6a8f2780-732d-11e9-99fa-23da40228140.png)

**Comment by mathieugerard** [comment]
Hi Guillaume.
Could you share the logs you are getting when trying to reopen the map?
Thanks

**Comment by EmeryGuillaume** [comment]
I have no log in the JS context so I guess that the issue is in the native code.
My android dev environment is broken so I can't provide you native log (I'll try to fix it but I can't promise, my android skills are limited).
I've reproduced the issue with your demo app (I've made a PR on its repo in order to make it working without the dev environment and using the last package on npm, so that anyone can use it).

**Comment by laszloblum** [comment]
Hi @EmeryGuillaume ,
Can you please send share me which android version you used?

**Comment by EmeryGuillaume** [comment]
I reproduced this issue on a galaxy S7 using android 8.0.0

**Comment by laszloblum** [comment]
@EmeryGuillaume Can you give me some  more info about the circumstances of the bug? I tried on my Android 8 device (Huawei P20 Lite) and it works fine.
Do you have the same bug on the demo app?

**Comment by EmeryGuillaume** [comment]
@laszloblum I just tested with a P20 Lite, to make sure that we both have the same configuration (EMUI 8.0 / Android 8.0).
I reproduce both on the viva technology app and on the demo app.
Open the app, then open the map, click on the home button then on the app icon (the app restart) -> the app is unable to open the map. 
Here is a video showing you the behavior:
[steps to reproduce.mov.zip](https://github.com/Mapwize/mapwize-cordova/files/3173596/steps.to.reproduce.mov.zip)

**Comment by laszloblum** [comment]
@EmeryGuillaume Very strange!
If I reopen the app through the task selector, it works fine, if I do it through I can it works as you described. There is something to do with the launchmode, I guess. I will check it!

**Comment by mathieugerard** [comment]
It seems the launchmode is the cause of the issue. It has been described in the doc.
