### ISSUE TITLE
[android] the app crash when closing and re-creating the mapwize view

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#4]
Using a samsung galaxy S7 running Android 8.0.0
Open the test app, click on CREATE
Use the back button to close the view and come back on the home screen
Re-click on CREATE
-> the app crash (if not, repeat this scenario)

See a video here:
[2019_04_11_10_28_02.mp4.zip](https://github.com/Mapwize/mapwize-cordova/files/3067681/2019_04_11_10_28_02.mp4.zip)

**Comment by mathieugerard** [comment]
Thanks for reporting this Guillaume. We'll have a look.

**Comment by laszloblum** [comment]
Fixed in commit 65285c0e5e6485bc3c99baaf9c62ebc7f4884c52

**Comment by mathieugerard** [comment]
@EmeryGuillaume Can you confirm you are not experiencing this issue anymore?

**Comment by EmeryGuillaume** [comment]
Hi @mathieugerard, I close this issue as the bug is fixed.
