### ISSUE TITLE
[ios] the offline mode doesn't work

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#5]
On iOS, using a device on airplane mode.
The map doesn't load.

![IMG_0449](https://user-images.githubusercontent.com/10091017/55964417-f9e4e480-5c74-11e9-9a2c-da66c8ab19d3.PNG)

**Comment by mathieugerard** [comment]
Hi Guillaume. That's right. The offline more still needs to be mapped, we are working on it.
Taking a venue offline will require a call to a special function called downloadVenueContent that will initiate the download of all the required data. That data is usually downloaded only on request when browsing online. We'll update this thread as the binding becomes available.

**Comment by mathieugerard** [comment]
The offline mode is now fully implemented on the offline branch. It will be merged to master shortly.

**Comment by mathieugerard** [comment]
The offline manager has been merged to master. Please refer to the documentation on how to download the venue data.
