### ISSUE TITLE
[android] the plugin doesn't work outside of the mapwize app demo

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#7]
The MapwizeActivity.java file import R using:
```
import org.mapwize.test.R;
```

This import should be dynamically set based on the app id (using a cordova hook for example).

**Comment by laszloblum** [comment]
Confirmed. Fixed in the above commit.

**Comment by mathieugerard** [comment]
@EmeryGuillaume Can you confirm you are not experiencing this issue anymore?

**Comment by EmeryGuillaume** [comment]
@mathieugerard the bug is fixed.
