### ISSUE TITLE
[android|ios] the languages folder isn't present in the mapwize-cordova repository

### ISSUE THREAD

**Issue by EmeryGuillaume** [Mapwize/mapwize-cordova#8]
The plugin uses hooks for locales that try to get languages in a folder at the root of the cordova project.

This languages folder is only present in your demo app: the plugin can't get them outside of this development environment.

The languages folder should be in the plugin directory and should be referenced in the hooks using for example:
```
    var platformSource = path.join(ctx.opts.projectRoot, 'plugins/mapwize-cordova-plugin/languages/ios');
```

**Comment by laszloblum** [comment]
For localization, please check the README file of the plugin.
It is intentional to have locales inside the project, not in plugin. This way, we can add more locales.

**Comment by laszloblum** [comment]
Thank you for your issue. I found a bug in case no language directory is found. It is fixed in the commit above.

**Comment by mathieugerard** [comment]
@EmeryGuillaume Can you confirm you are not experiencing this issue anymore?

**Comment by EmeryGuillaume** [comment]
Hello @mathieugerard,
I don't experience the issue anymore, thanks.
